name: neurasp_gpt
channels:
  - pytorch
  - potassco
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohttp=3.8.1=py39hb9d737c_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.6.0=h6a678d5_0
  - arrow-cpp=19.0.0=h16717c6_5
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.8.3=py39h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - clingo=5.8.0=py39h3fd9d12_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.2.1=py39hdb19cb5_1
  - cpuonly=2.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=3.6.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h5eee18b_0
  - dill=0.3.8=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py39h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.59.2=py39hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py39h5eee18b_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - hf-xet=1.1.8=py39h84c0859_0
  - huggingface_hub=0.34.3=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib_resources=6.5.2=py39h06a4308_0
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h362ad58_1
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=cpu_openblas_h526855f_4
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.1.0=py39h5eee18b_0
  - multiprocess=0.70.15=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.2.1=py39h06a4308_0
  - nomkl=3.0=0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39hc213724_1
  - numpy-base=1.26.4=py39hf387b04_1
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - opentelemetry-api=1.37.0=py39h06a4308_0
  - orc=2.1.1=hd396ef6_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py39h277b779_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.3.0=py39hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=19.0.0=py39h7934f7d_2
  - pycparser=2.23=py39h06a4308_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py39h5eee18b_0
  - python_abi=3.9=2_cp39
  - pytorch=2.5.1=cpu_openblas_py39hff96616_4
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - regex=2025.9.1=py39hee96239_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.5.3=py39h922eef2_0
  - seaborn=0.13.2=py39h06a4308_3
  - setuptools=78.1.1=py39h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.5.1=h5eee18b_2
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.14.0=py39h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tokenizers=0.21.0=py39ha92566c_0
  - torchaudio=2.5.1=py39_cpu
  - torchvision=0.20.1=cpu_py39h1c79344_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.55.2=pyhd8ed1ab_0
  - typing-extensions=4.15.0=py39h06a4308_0
  - typing_extensions=4.15.0=py39h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f98852_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39hb9d737c_2
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - einops==0.8.1
      - opencv-python-headless==4.12.0.88
prefix: /home/esteban/.conda/envs/neurasp_gpt
